name: 'Target action'
description: 'An action from the target ref'
inputs:
  super_secret:
    description: 'The secret to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Show info
      run: |
        echo "This action is running from the target ref."
        echo "The base64 of the secret is $(printf '%s' "${SUPER_SECRET}" | base64)."
      shell: bash
      env:
        SUPER_SECRET: ${{ inputs.super_secret }}
